{
 "title": "Webapp Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Get User Count", "type": "gauge", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "count" ] } } },
  {
   "title": "Create User Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "count_create_user" }
   ]
  },
  { "title": "Get Watch Count", "type": "gauge", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "count" ] } } },
  {
   "title": "Update Watch Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "count_update_watch" }
   ]
  },
  {
   "title": "Update User Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "count_update_user" }
   ]
  },
  {
   "title": "Add Watch Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "count_add_watch" }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_add_watch" },
    { "expr": "count_update_watch" },
    { "expr": "count_delete_watch" }
   ]
  },
  {
   "title": "Users Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_create_user" },
    { "expr": "count_update_user" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Histograms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(time_kafka_calls_bucket[5m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(timed_db_calls_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "DB Calls Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "timed_db_calls_bucket" }
   ]
  }
 ]
}